### ISSUE TITLE
populate verb type hierarchy

### ISSUE THREAD

**Issue by leoalenc** [LR-POR/PorGram#19]
@arademaker, diferentes estratégias podem ser utilizadas para povoar a hierarquia de tipos verbais baseada na valência: 

1. _treebanks_, como o UD Bosque e o Tycho Brahe
2. dicionários gerais on-line com informações sobre a regência verbal, como o Michaelis
3. dicionários de regimes verbais como o de Francisco Fernandes, ou de valências, como o [dicionário gramatical de verbos](http://editoraunesp.com.br/catalogo/8571390096,dicionario-gramatical-de-verbo) organizado por Francisco da Silva Borba et al. 
3. gramáticas de referência, como Cunha e Cintra (1985) e Mateus et al. (1989)
3. artigos e monografias da área de linguística descritiva, linguística computacional ou PLN, especialmente os trabalhos de Mario Perini e Márcia Cançado e colaboradoras, da UFMG, minha dissertação de mestrado e tese de doutorado, tese do meu orientando Jessé Mourão etc.
4. classes verbais da BrGram
4. redes léxico-semânticas do tipo da WordNet
5. tipos verbais da ERG, da gramática do espanhol construída por meio da Matriz Gramatical etc.
6. VerbNet-BR (http://www.nilc.icmc.usp.br/verbnetbr/), Propbank-Br (http://www.nilc.icmc.usp.br/portlex/, versão 1.1 anotou parte do Bosque e constriui uma lista de senses a partir dos senses de EN). E finalmente, https://github.com/System-T/UniversalPropositions.
7. Treebank do UD Deep 
8. Tools como https://github.com/hltcoe/PredPatt/

**Comment by arademaker** [comment]
@leoalenc combinei agora com @wellington36 que vamos completar 

https://github.com/LR-POR/ud-matrix/blob/master/examples.conllu

A idéia é que cada exemplo da sua tabela acima será analisado por UDPipe, e no cabeçalho termos o tipo em PorGram e a query que traz os padrões UD que ocorrem no corpus bosque

**Comment by leoalenc** [comment]
> > Seria uma brincadeira interessante extrair os tipos de verbos da gramática e construir _queries_ para extração de exemplos no Bosque a partir das definições dos tipos, traduzindo HPSG para UD.
> 
> na tabela, o tipo `bare-inf-aux-lex` é definido como:
> 
> > O complemento oracional está no infinitivo "nu" não flexionado.
> 
> estou imaginando que 'nu' é 'não', é isso? Bem, assumindo isso, usei o lkb para análise a sentença dada como exemplo. usando a opção de `highlight chart nodes`:
> 
> <img alt="image" width="1082" src="https://user-images.githubusercontent.com/86403/136859716-ad7a8877-5e42-44db-94e8-b26c161fbe47.png">
> 
> então o tipo instanciado para o verbo é `inf-trans-first-arg-control-ve`. Tentei entender o tipo, olhando a feature structure, mas confesso que não faço idéia como seguir daqui na tentativa de identificar os complementos. Vejo uma feature VAL que tem uma estrutura que também tem uma feature VAL
> 
> <img alt="image" width="1187" src="https://user-images.githubusercontent.com/86403/136860692-abb2c855-cc37-4c63-9d80-52256da91810.png">
> 
> Se navego pela unfilled FS, chego a definição do tipo `trans-first-arg-control-verb-lex`:
> 
> <img alt="image" width="528" src="https://user-images.githubusercontent.com/86403/136860783-87ca8c14-a557-4398-9232-15c654b93bb2.png">
> 
> Mas partimos do tipo `bare-inf-aux-lex`, e este nem foi mencionado na análise da sentença pelo LKB.

@arademaker , *nu* é a tradução de *bare*. Na linguística formal, especialmente de base gerativa, em modelos como Minimalism, HPSG etc., diz-se que um sintagma XP é *bare* quando não contém um especificador ou algum outro item análogo (que não um complemento ou adjunto) expandindo a projeção do núcleo X, em línguas como o inglês e o português esse item se situa na periferia esquerda. Desse modo, *bare NP* é o sintagma nominal *gold* em *gold is expensive* por oposição ao sintagma nominal de *this car is expensive*. No caso de *infinitivo nu*, em inglês é o inifinitivo de *Mary can swim* por oposição ao de *Mary wants to swim*, veja este [dicionário](https://dictionary.cambridge.org/dictionary/english/bare-infinitive#:~:text=in%20grammar%2C%20the%20infinitive%20form,forms%2C%20tenses%20%26%20types%20of%20verbs) de termos técnicos, por exemplo. Estou analisando as preposições que introduzem os infinitivos como complementadores, seguindo análises gerativas do francês, por exemplo, exercendo, portanto, papel análogo ao *to* do inglês, também analisado como complementador por diversos autores, diferentemente de Wasow, Sag e Bender (2003, p. 361), que analisam esse *to* como auxiliar.  
@arademaker, peço desculpa pela confusão, mas você apontou um erro importante na minha tabela, decorrente de correção que fiz posteriormente, documentada em #45. Obrigado!
Isso aponta para um problema no desenvolvimento da gramática: como manter atualizada a documentação, diante de constantes mudanças no código? Acredito que o desenvolvimento em Java e Python têm algo a ensinar. As documentações são geradas automaticamente a partir do código, não é?
Quando fiz a tabela, ainda não sabia como implementar o controle do sujeito e do objeto etc. manualmente. Controle não é suportado pelo questionário. Na gramática atual, temos no léxico:

`grep -En "bare\-inf\-aux\-lex" *.tdl`

> lexicon.tdl:831:poder := bare-inf-aux-lex &
> lexicon.tdl:835:dever := bare-inf-aux-lex &
> lexicon.tdl:839:parecer := bare-inf-aux-lex &
> lexicon.tdl:843:precisar := bare-inf-aux-lex &
> lexicon.tdl:847:costumar := bare-inf-aux-lex &
> portuguese.tdl:475:bare-inf-aux-lex := subj-raise-aux-with-pred &

`grep -En "inf-trans-first-arg-control" *.tdl`

> control-verbs.tdl:1:preferir_1 := inf-trans-first-arg-control-verb-lex &
> control-verbs.tdl:5:prometer_2 := inf-trans-first-arg-control-verb-lex &
> control-verbs.tdl:9:planejar := inf-trans-first-arg-control-verb-lex &
> control-verbs.tdl:13:ousar :=  inf-trans-first-arg-control-verb-lex &
> control-verbs.tdl:17:desejar_2 :=inf-trans-first-arg-control-verb-lex &
> control-verbs.tdl:21:querer_2 :=inf-trans-first-arg-control-verb-lex &
> control-verbs.tdl:25:saber_3 :=inf-trans-first-arg-control-verb-lex &
> control-verbs.tdl:29:detestar_4 :=inf-trans-first-arg-control-verb-lex &
> control-verbs.tdl:33:lamentar_3 :=inf-trans-first-arg-control-verb-lex &
> control-verbs.tdl:37:conseguir := inf-trans-first-arg-control-verb-lex &
> control-verbs.tdl:41:tentar := inf-trans-first-arg-control-verb-lex &
> control-verbs.tdl:45:dizer_3 := inf-trans-first-arg-control-verb-lex &
> control-verbs.tdl:50:acreditar_2 := inf-trans-first-arg-control-verb-lex &
> control-verbs.tdl:54:tentar := inf-trans-first-arg-control-verb-lex &
> control-verbs.tdl:58:tencionar := inf-trans-first-arg-control-verb-lex &
> my-portuguese.tdl:453:inf-trans-first-arg-control-verb-lex := trans-first-arg-control-verb-lex & [ ARG-ST.REST.FIRST.LOCAL.CAT.HEAD.FORM infinitive].
>  

Vemos que, se a tabela fosse criada automaticamente a partir da gramática e dos exemplos, esse equívoco não teria ocorrido! 
Sobre a inspeção dos tipos, eu pessoalmente acho mais legível olhar diretamente o código TDL no emacs. O formato é mais amigável. 
Conclusão: no exemplo que você analisou no LKB, o tipo de *querer* é mesmo `inf-trans-first-arg-control-verb-lex` e não `bare-inf-verb-lex` como está na tabela.  Esse último tipo é dos verbos de alçamento do sujeito, tratados como auxiliares pela Grammar Matrix.

**Comment by leoalenc** [comment]
> > 1. É possível que, no futuro, quando a atual hierarquia de tipos for expandida para incluir determinados verbos com objetos preposicionados (por exemplo, _colocar_), precisemos buscar por exemplos com _obl_ (@arademaker, a propósito, como o Bosque anota esse tipo de verbo? Se o alvo for realizado como _iobj_, então entra nos agrupamentos.). No momento, porém, não temos verbos desse tipo na gramática.
> 
> obj pelo que vi em alguns casos: http://match.grew.fr/?corpus=UD_Portuguese-Bosque@dev&custom=6168589922e1a

@arademaker , no exemplo abaixo, extraído desses resultados, o PP complemento de _colocar_ é um `obl`:

> text = Uma vantagem de 1m34s sobre os segundos, José Carlos Macedo / Miguel Borges, em Renault Clio 16V, garante ao piloto do Lancia HF Integrale uma forte dose de tranquilidade para conseguir a vitória na prova, o que o colocaria em excelente posição para a conquista do título.
> sent_id = CP99-4
> source = CETEMPúblico n=99 sec=des sem=93a
> id = 526
> 

http://match.grew.fr/data/61688295d560b/525.svg

Nesse caso, o `obl` integra a valência verbal. O problema é que, noutros exemplos, como o primeiro da lista que você compilou, não é argumento do verbo, constituindo, portanto, um adjunto:

http://match.grew.fr/data/61688295d560b/198.svg

Nesse caso, _nos dias certos_ não constitui o alvo do deslocamento, subentendido (infere-se que nos locais apropriados, determinados pelas autoridades, por exemplo, na calçada), mas uma circunstância temporal do evento de colocar.

**Comment by wellington36** [comment]
> @leoalenc Acredito que entendi o que você está pedindo, mas para confirmar gostaria de ver esse exemplo que você comentou, só que acho que você colocou o link errado pois nenhum verbo dentre separar, colocar e recolher está na sentença do link.

@lucasrct, o verbo em questão é este, marcado:

![image](https://user-images.githubusercontent.com/61877847/137413234-1379a885-8d94-4a1a-bcb1-35a91a449120.png)

**Comment by lucasrct** [comment]
Criei aqui um script capaz de extrair os filhos de cada verbo no bosque, só estou ainda pensando na melhor maneira de lidar guardar o resultado e interpretar. 

Um exemplo, 

o verbo 'comer' aparece 16 vezes no corpus de treino do bosque, sendo que suas configurações de filhos que ocorreram no bosque foram:

['advmod', 'aux', 'cc', 'obj'], 
['mark', 'nsubj', 'obj'], 
['conj', 'mark', 'obj'],
['expl', 'nsubj', 'obl'], 
['aux', 'obj', 'obl'], 
['conj', 'conj', 'conj', 'mark'], 
['obl'], 
['obj'], 
['conj', 'conj', 'mark', 'obl'], 
[], 
['cc', 'nsubj', 'obj'], 
['cc', 'obl'], 
['mark', 'obj'], 
['mark']

É esse o caminho? Existe alguma deprel que podemos excluir da agregação? (Já removi as deprel do formato 'punct')

**Comment by leoalenc** [comment]
> @leoalenc criei aqui um script capaz de extrair os filhos de cada verbo no bosque, só estou ainda pensando na melhor maneira de lidar guardar o resultado e interpretar. 
> 
> 
> 
> Um exemplo, 
> 
> 
> 
> o verbo 'comer' aparece 16 vezes no corpus de treino do bosque, sendo que suas configurações de filhos que ocorreram foram:
> 
> 
> 
> ['advmod', 'aux', 'cc', 'obj'], 
> 
> ['mark', 'nsubj', 'obj'], 
> 
> ['conj', 'mark', 'obj'],
> 
> ['expl', 'nsubj', 'obl'], 
> 
> ['aux', 'obj', 'obl'], 
> 
> ['conj', 'conj', 'conj', 'mark'], 
> 
> ['obl'], 
> 
> ['obj'], 
> 
> ['conj', 'conj', 'mark', 'obl'], 
> 
> [], 
> 
> ['cc', 'nsubj', 'obj'], 
> 
> ['cc', 'obl'], 
> 
> ['mark', 'obj'], 
> 
> ['mark']
> 
> 
> 
> É esse o caminho? Existe alguma deprel que podemos excluir da agregação? (Já removi as deprel do formato 'punct')
> 
> 
> 
> 

@lucasrct , Muito bom! Sim, várias dependências não são relevantes,￼estamos interessados apenas no seguinte:￼
￼
nsubj sujeito￼
obj objeto direto￼
iobj objeto indireto￼
xcomp 
ccomp 
csubj 
expl

Para o objeto e o objeto indireto, precisamos do _adp_ ligado via _case_.
Para _xcomp_, _csubj_ e _ccomp_, precisamos das conjunções ligadas por _mark_.￼
Também são necessárias mais algumas informações adicionais, estão nos comentários, mas posso listar depois.￼

**Comment by leoalenc** [comment]
@lucasrct , lembrando que, no meu comentário acima, objeto é _obj_ e objeto indireto é￼￼ _iobj_.

**Comment by leoalenc** [comment]
@lucasrct , veja novamente ￼a lista de dependentes relevantes:￼
> nsubj sujeito￼
> obj objeto direto￼
> iobj objeto indireto￼
> xcomp 
> ccomp 
> csubj 
> expl
> 
> Para o objeto _obj_ e o objeto indireto _iobj_, precisamos do _adp_ ligado via _case_.
> Para _xcomp_, _csubj_ e _ccomp_, precisamos das conjunções ligadas por _mark_.￼
> Também são necessárias mais algumas informações adicionais, estão nos comentários, mas posso listar depois.￼
>

**Comment by leoalenc** [comment]
@lucasrct , veja este outro exemplo:

http://match.grew.fr/data/616adee240cc5/42.svg

Foi retirado desta *query* elaborada pelo @wellington36:

http://match.grew.fr/?corpus=UD_Portuguese-Bosque@dev&custom=6168622521909

Eu preciso obter, para cada verbo, de cada sentença do corpus, listas como as seguintes:

**Lista 1**: 
```
VERB:pedir+Ind+Sing+3+Past+Fin
nsubj
iobj:case+ADP+a
ccomp:mark+SCONJ+que+Sub
xcomp:VERB+transformar+Inf
```

**Lista 2**: 
```
VERB:empenhar+Sub+Plur+3+Pres+Fin
expl:PRON+se+Acc+Masc+Plur+3+Pres
obj:case+ADP+em
```

**Lista 3**:
```
VERB:transformar+Inf
obj:case+ADP+em
```

Coloquei os dependentes de cada um dos três verbos num formato vertical para facilitar a leitura, mas a saída inicial do algoritmo deve ser, para cada sentença, uma lista de listas:

```
VERB:pedir+Ind+Sing+3+Past+Fin nsubj iobj:case+ADP+a ccomp:mark+SCONJ+que+Sub xcomp:VERB+transformar+Inf

VERB:empenhar+Sub+Plur+3+Pres+Fin expl:PRON+se+Acc+Masc+Plur+3+Pres obj:case+ADP+em

VERB:transformar+Inf obj:case+ADP+em
```

Observe o seguinte sobre a notação utilizada:

1. Eu não transcrevo os atributos, mas apenas os valores deles, para economizar espaço.
2. No caso de _obj_ e _iobj_, extraio a _ADP_ ligada por _case_. 
3. No caso de _ccomp_,  extraio a conjunção ligadas por _mark_ e o modo do verbo encaixado, ou seja, _empenhar_ que está ligado a _pedir_ via _ccomp_. 
4. No caso de _xcomp_, extraio os valores dos atributos do verbo (se houver uma conjunção subordinada, também preciso de suas informações, como fiz com o _ccomp_). 
5. Extraio os valores dos atributos do _expl_.

Obrigado por sua colaboração. Caso tenha dúvidas, formule-as aqui e, se eu demorar a responder, pode enviar mensagem alertando pelo Telegrama.

**Comment by leoalenc** [comment]
@lucasrct, vi agora que _pedir_ no exemplo dado rege também um _obj_ realizado pelo pronome _se_, que deverá entrar na lista:

```
VERB:pedir+Ind+Sing+3+Past+Fin
nsubj
iobj:case+ADP+a
ccomp:mark+SCONJ+que+Sub
obj
xcomp:VERB+transformar+Inf
```

@arademaker, a propósito, há pelo menos dois erros na anotação desse exemplo. Vou abrir _issue_ no repositório do Bosque: 

1. Esse pronome _se_ na função de _obj_ não se vincula a _pedir_, mas a _transformar_!   
2. Deveria estar anotado como _expl_.
3. Esse _xcomp_, na verdade, não é um _xcomp_ de _pedir_, pois não constitui argumento nuclear.

**Comment by leoalenc** [comment]
@lucasrct , esqueci do verbo _surgir_ no [exemplo](http://match.grew.fr/data/616adee240cc5/42.svg) dado acima:

**Lista 4**
```
nsubj
VERB:surgir+Sub+Plur+3+Pres+Fin
```

Esse verbo tem um filho ligado via _mark_, no entanto, como esse verbo vincula-se via _advcl_ a _pedir_, essa informação não é relevante.

**Comment by lucasrct** [comment]
@leoalenc Aqui está a lista com os verbos que possuem 2 ccomp (não existe casos de mais de dois no corpus de treino)


```

sent_id: CP233-4
Verbo: gostar (gostaria)
Frase: Continuo a dizer que acho bem que os Barmens saibam que a Delegação está aberta para todos eles,e gostaria imenso que eles aparecessem em vez de uma vez por mês, dez vezes porque temos todas as condições criadas para os receber.

sent_id: CP387-2
Verbo: acreditar (acreditar)
Frase: os cubanos podem simplesmente não acreditar que os Estados Unidos os retenham perpetuamente em Guantanamo, ou que os enviem para outros países, e então a fuga continuará.

sent_id: CP419-3
Verbo: acrescentar (acrescenta)
Frase: O jornal acrescenta que os gibraltinos receiam que a medida seja um primeiro passo para os britânicos desistirem da soberania sobre o rochedo, situado num promontório no sul de Espanha, devolvendo-o aos espanhóis.

sent_id: CP775-6
Verbo: crer (creio)
Frase: Não creio que o povo americano queira que eu fizesse isso».

sent_id: CF395-5
Verbo: ver (vi)
Frase: Nunca vi um partido render-se tão rápida e incondicionalmente como o PT está fazendo.
```

**Comment by leoalenc** [comment]
> @leoalenc Aqui está a lista com os verbos que possuem 2 ccomp (não existe casos de mais de dois no corpus de treino)
> 
> 
> sent_id: CP419-3
> Verbo: acrescentar (acrescenta)
> Frase: O jornal acrescenta que os gibraltinos receiam que a medida seja um primeiro passo para os britânicos desistirem da soberania sobre o rochedo, situado num promontório no sul de Espanha, devolvendo-o aos espanhóis.
> 


@lucasrct, muio obrigado! Não examinei a árvore dependencial de todas essas ocorrências, porque a busca pelo padrão 

```pattern { 
	VERB [ upos=VERB ]; 
    FILHO1 [ ];
    FILHO2 [ ];
    FILHO3 [ ];
    
    VERB -[nsubj]-> FILHO1;
    VERB -[ccomp]-> FILHO2;
	VERB -[ccomp]-> FILHO3;
}
pattern { 
	VERB [ upos=VERB ]; 
    FILHO1 [ ];
    FILHO2 [ ];
    FILHO3 [ ];
    
    VERB -[nsubj]-> FILHO1;
    VERB -[ccomp]-> FILHO2;
	VERB -[ccomp]-> FILHO3;
}
```
 em http://match.grew.fr/?corpus=UD_Portuguese-Bosque@2.8 retornou apenas este resultado, correspondente ao exemplo acima:

http://match.grew.fr/data/616c532de8717/2198_1.svg

Podemos observar, @arademaker e @wellington36,  que o analisador estatístico sistematicamente comete o mesmo tipo de erro que apontei antes, atribuindo ao primeiro verbo que rege um `ccomp`, ou seja, _acreditar_ no exemplo em tela, um outro `ccomp` da mesma sentença, regido pelo verbo encaixado, i.e., _recear_.

**Comment by lucasrct** [comment]
Estou pensando aqui na melhor maneira para exibir os dados @leoalenc, por exemplo:

Verbos que possuem como subconjunto de relações [nsubj,obj]


`[situar, continuar, manter, esperar, deixar, ser, correr, querer, fugir, ir, encontrar, gastar, juntar, reivindicar, faltar, lembrar, considerar, especializar, dispor, encomendar, vir, financiar, sair, pagar, acontecer, fazer, dar, desaparecer, perder, apresentar, ter, denominar, permitir, gravar, estar, dizer, desenvolver, compor, comercializar, confrontar, falar, integrar, reagir, enviar, ver, emitir, informar, afirmar, interpretar, entender, recordar, suspender, gerir, compreender, destinar, mostrar, justificar, registar, dirigir, cair, haver, admitir, ficar, ganhar, abranger, parar, aumentar, elaborar, totalizar, usufruir, garantir, excluir, traçar, revelar, resultar, cobrir, referir, montar, testar, acabar, ceder, pôr, gerar, pedir, transformar, abrir, comedir, cumprimentar, declarar, resolver, chegar, ajudar, terminar, contar, decidir, abandonar, instalar, tomar, afastar, evocar, comprar, passar, saber, concluir, desonrar, iniciar, segurar, nascer, lutar, gostar, assinar, ler, defender, tratar, escrever, imitar, atribuir, pertencer, interrogar, contestar, vencer, marcar, conseguir, adaptar, recuar, insistir, comandar, desempenhar, condenar, escolher, apontar, manifestar, levar, obrigar, disputar, tentar, organizar, acusar, privilegiar, oferecer, rondar, criar, convencer, acolher, aceitar, parecer, dividir, traduzir, identificar, aderir, englobar, ocupar, usar, prever, receber, pisar, presidir, depender, respeitar, comentar, falhar, lançar, assassinar, mandar, reafirmar, responder, preferir, expulsar, significar, começar, produzir, publicar, decretar, opor, bater, ignorar, chamar, cumprir, assegurar, denunciar, destacar, nomear, ocorrer, sublinhar, perturbar, proibir, aperceber, buscar, utilizar, seguir, partir, patrocinar, cantar, aguardar, permanecer, coordenar, desembarcar, editar, compatibilizar, tornar, coincidir, descer, reduzir, visar, sofrer, divulgar, realizar, morrer, alertar, recomendar, tocar, evitar, impor, temer, fechar, adiar, provocar, recolher, conhecer, acentuar, separar, colocar, explicar, estabelecer, anunciar, renovar, achar, preocupar, pensar, beneficiar, formar, ensinar, aprender, citar, avaliar, esclarecer, fundar, deter, bloquear, perceber, recusar, cometer, destruir, tirar, contactar, esquecer, desmentir, encerrar, movimentar, expor, guardar, noticiar, detectar, distribuir, inclinar, prender, substituir, reclamar, acompanhar, ligar, cancelar, preparar, incidir, suspeitar, aproveitar, desencadear, levantar, perguntar, acrescentar, promover, reunir, incorporar, propor, manipular, bastar, vender, perpetuar, proteger, desconhecer, descobrir, bordejar, frequentar, servir, apanhar, apurar, assistir, determinar, baixar, pretender, indeferir, derivar, superar, prosseguir, atenuar, mudar, consistir, brincar, mentir, partilhar, aprovar, remeter, exigir, criticar, praticar, comparecer, analisar, construir, confirmar, estudar, recair, apoiar, compensar, acreditar, negar, incluir, comprometer, entregar, liderar, inaugurar, caracterizar, recriar, calcular, atinjir, verificar, atingir, suscitar, decorrer, defrontar, aliviar, treinar, conter, inventar, torturar, procurar, interromper, abordar, equilibrar, deitar, negociar, afectar, desenhar, libertar, crescer, ameaçar, virar, viver, meter, valorizar, arriscar, teorizar, competir, alimentar, aliar, apelar, concordar, possuir, escapar, prestar, incomodar, aguentar, ouvir, consumir, discutir, demonstrar, basear, cerrar, abraçar, arrumar, percorrer, reiterar, obter, alegar, submeter, fornecer, representar, governar, notificar, custar, atravessar, contratar, trazer, impedir, preservar, diminuir, observar, ilustrar, chancelar, desenterrar, combater, consagrar, instituir, ascender, importar, elevar, poupar, provar, preconizar, repetir, valer, encaminhar, matar, definir, jogar, envolver, relatar, concentrar, conceber, caber, estrear, anular, merecer, reforçar, constituir, apreender, transportar, confiscar, enfrentar, proceder, retirar, recorrer, reconhecer, interessar, filmar, irromper, esgotar, subir, render, transmitir, dispensar, contribuir, completar, medir, regulamentar, apostar, ultrapassar, conquistar, dançar, atear, chorar, esconder, assumir, agradar, sustentar, trabalhar, limitar, adoptar, delimitar, descarregar, alcançar, chumbar, radicalizar, inverter, amar, debater, conviver, apagar, localizar, assaltar, controlar, ferir, evadir, efectuar, forçar, contrastar, cortar, durar, comer, esticar, ditar, converter, atender, autorizar, retomar, votar, corrigir, precisar, aplicar, confessar, melhorar, ampliar, leccionar, dominar, rodear, animar, suceder, assentar, soar, exercer, agendar, telefonar, optar, capturar, escutar, exprimir, emocionar, saltar, golear, reflectir, disfrutar, pressionar, quebrar, deparar, antecipar, estranhar, depositar, experimentar, contemplar, alterar, demover, falsificar, beber, saborear, eliminar, derrotar, causar, sucumbir, chefiar, comprovar, implicar, validar, participar, exportar, despedir, empregar, herdar, conservar, esvaziar, tolerar, solicitar, pegar, acertar, variar, influenciar, favorecer, rejeitar, associar, atrair, desfrutar, conduzir, rubricar, conferir, sugerir, exibir, recuperar, evidenciar, requerer, secar, festejar, suportar, recolocar, sentar, enxugar, submergir, relacionar, seduzir, subscrever, indicar, dinamizar, cercar, salvar, convocar, obedecer, disparar, atacar, acorrer, visitar, corresponder, posicionar, ordenar, equivaler, alinhar, desejar, formalizar, misturar, encetar, trocar, refutar, atrasar, carecer, prometer, orientar, povoar, soltar, executar, arrasar, datar, administrar, estimar, abafar, devorar, saudar, lidar, averbar, doar, estragar, apressar, realçar, motivar, reservar, angariar, cobrar, celebrar, fiscalizar, agravar, conceder, triturar, revestir, facilitar, dificultar, invadir, romper, livrar, residir, cheirar, investir, consultar, massacrar, relançar, assinalar, questionar, impressionar, desculpar, calar, abrandar, ponderar, aconselhar, olhar, inundar, responsabilizar, acarretar, retratar, minimizar, proferir, renunciar, afunilar, iluminar, protagonizar, enunciar, prejudicar, reter, curvar, contrariar, simbolizar, inscrever, homenagear, mobilizar, elogiar, confundir, namorar, mexer, divergir, ingerir, desactivar, penalizar, fabricar, ostentar, entornar, revogar, recear, desistir, reconciliar, lavar, possibilitar, enterrar, acotovelar, aceder, verter, interiorizar, delapidar, acumular, atestar, exteriorizar, reescrever, prognosticar, distanciar, reexaminar, vacinar, bombardear, somar, aturar, honrar, apaziguar, resistir, necessitar, agudizar, culpabilizar, delinear, comemorar, desencorajar, instaurar, admirar, encabeçar, concernir, planear, esfregar, diluir, cuidar, sonhar, carregar, regularizar, incitar, conciliar, esmagar, demolir, atirar, articular, preencher, desprender, enriquecer, diferir, esboçar, alugar, suavizar, enervar, adivinhar, declinar, sobrar, violar, processar, estipular, balizar, rivalizar, redundar, oficiar, brindar, vampirizar, complementar, atordoar, cultivar, regular, degolar, pregar, vençer, excitar, vedar, agrupar, estimular, enjeitar, ornar, balbuciar, assimilar, esforçar, provir, amealhar, cumprimir, resumir, envergonhar, normalizar, igualar, perigar, desempatar, consolidar, digladiar, habitar, propiciar, restringir, prescindir, fracturar, especular, contaminar, legitimar, denegrir, derrubar, vasculhar, descolar, desagradar, frustrar, encarnar, facturar, preceder, denotar, revisitar, anteceder, narrar, dardejar, sorrir, explicitar, escalar, liberar, menosprezar, independer, afetar, plantar, desvirtuar, conectar, torcer, atuar, projetar, descartar, conversar, qualificar, priorizar, desmitificar, refletir, selecionar, faturar, planejar, adotar, rebatizar, abalar, neutralizar, configurar, irritar, omitir, desrespeitar, padecer, fascinar, barrar, registrar, acatar, colecionar, conclamar, debitar, reavaliar, zerar, desinterditar, adulterar, idolatrar, personificar, reinaugurar, restabelecer, desconfiar, entrevistar, expedir, modificar, fundamentar, zonear, retardar, renegociar, decolar, camuflar, acostumar, supervisionar, impugnar, engordar, abrigar, desengavetar, emoldurar, mimetizar, reabrir, consubstanciar, engrossar, acionar, circundar, repelir, reinstalar, municiar, debilitar, varrer, coroar, embutir, papar, incorrer, tatuar, resgatar, forjar, traficar, desaconselhar, desdenhar]
`

Não acho que apenas isso seja uma informação suficiente, mas ao mesmo tempo, não acho que apenas alguns exemplos de alguns verbos seria o suficiente para decidirmos sobre todos.

**Comment by lucasrct** [comment]
Um exemplo do output que você deu a ideia acima: Todas as formas de ocorrência do verbo esperar
```
esperar+Ger ccomp VERB+mark+SCONJ+que nsubj 
esperar+Ind+Sing+3+Pres+Fin xcomp ADJ+terminado nsubj 
esperar+Ind+Plur+1+Imp+Fin obj 
esperar+Ind+Sing+1+Pres+Fin ccomp VERB+mark+SCONJ+que nsubj 
esperar+Ind+Sing+3+Imp+Fin xcomp VERB+aparecer 
esperar+Ind+Plur+3+Imp+Fin xcomp VERB+encontrar 
esperar+Inf obj 
esperar+Ger obj 
esperar+Ind+Plur+3+Pres+Fin xcomp VERB+ver nsubj 
esperar+Ind+Sing+1+Pres+Fin ccomp VERB+mark+SCONJ+que 
esperar+Ind+Sing+1+Pres+Fin obj 
esperar+Inf obj PRON+se+Acc+Masc+Plur+3+Prs
esperar+Sub+Sing+3+Pres+Fin xcomp VERB+subir 
esperar+Ind+Sing+3+Pres+Fin xcomp VERB+encontrar nsubj 
esperar+Ger obj nsubj 
esperar+Ind+Plur+1+Pres+Fin xcomp VERB+continuar 
esperar+Ind+Plur+3+Imp+Fin obj nsubj 
esperar+Ind+Sing+3+Pres+Fin obj iobj nsubj 
esperar+Ind+Sing+1+Pres+Fin xcomp VERB+vir 
esperar+Ind+Plur+3+Pres+Fin obj iobj nsubj 
esperar+Ind+Sing+1+Pres+Fin 
esperar+Ind+Plur+3+Pres+Fin obj nsubj 
esperar+Ind+Plur+3+Pres+Fin PRON+se+Acc+Fem+Plur+3+Prs
esperar+Inf ccomp VERB+mark+SCONJ+que 
esperar+Ind+Sing+1+Imp+Fin obj nsubj 
esperar+Ind+Sing+3+Pres+Fin obj nsubj 
esperar+Ind+Sing+1+Pres+Fin xcomp VERB+sair 
esperar+Ind+Sing+3+Past+Fin obj nsubj 
esperar+Ind+Sing+1+Pres+Fin xcomp ADJ+último 
esperar+Ind+Sing+3+Pres+Fin ccomp VERB+mark+SCONJ+que nsubj 
esperar+Ger ccomp VERB+mark+SCONJ+que
```

**Comment by arademaker** [comment]
> Um exemplo do output que você deu a ideia acima: Todas as formas de ocorrência do verbo esperar

Acho que também precisamos saber a morfologia do verbo da clausula subordinada...

**Comment by leoalenc** [comment]
> para determinar a forma passiva, o que podemos usar? me parece que procurar pelo AUX filho do verbo que é um aux:pass é o mais correto/seguro:
> 
> 
> 
> ```
> 
> % awk '$8 ~ /aux:pass/' *.conllu  | wc -l
> 
>     1194
> 
> % awk '$8 ~ /nsubj:pass/' *.conllu  | wc -l
> 
>      999
> 
> ```
> 
> 
> 
> nem todas as formas passivas tem o sujeito da passiva.

@arademaker , sim, o auxiliar da passiva é importante, outro indício é a forma do verbo, que deve estar no particípio passado.￼
Essa informação é crucial porque, do contrário, não será feita uma modelação correta da valência partir das molduras encontradas no corpus:
Por exemplo, imaginemos o seguinte exemplo fictício: _as casas foram destruídas pela enchente_. A moldura extraída será de apenas um sujeito _nsubj_. Se eu não tiver a informação sobre o uso passivo do verbo, eu vou concluir erroneamente que se trata de um uso intransitivo do verbo, como, por exemplo: as casas destruíram. Por sinal, esse uso não é corrente.￼￼￼￼￼ O agente da passiva não é importante, no exemplo dado, _pela enchente_, ￼￼acho que ele está sendo analisado no bosque como _obl_, certo?￼

**Comment by arademaker** [comment]
> Quanto à informação da voz passiva, visto que, pelo que entendi, não existe um método automatizável e seguro de garantir se determinado verbo está na voz passiva, acredito que o ideal seria não colocar por enquanto, visto que dependeria de algumas inferências e poderíamos agregar mais ruido ao processo, o que acham?

eu acho que temos sim uma forma concreta de identificar, são os verbos que tem algum dependente `aux:pass` que é AUX.

**Comment by arademaker** [comment]
See d715dff, lexicon file extracted from bosque. code will be provided by @leoalenc but it uses the tools/etc/valence.py code from @lucasrct

**Comment by leoalenc** [comment]
Por sugestão de @arademaker, estou fechando a *issue*, que é muito ampla, devendo acompanhar todo o desenvolvimento da gramática. Passarei a abrir _issues_ sobre grupos específicos de verbos, como, por exemplo, já fiz em #66 e #67.

**Comment by arademaker** [comment]
Por grupos de verbo ou por recurso usado para extração de léxico. Podemos ter um issue para extração bosque , outro para extração do dhbb, outro para extração da wordnet etc
