### ISSUE TITLE
eliminate unnecessary ambiguity

### ISSUE THREAD

**Issue by leoalenc** [LR-POR/PorGram#44]
No momento, a gramática produz duas árvores sintáticas para sentenças com verbos declarativos, como, por exemplo:

>26 o cachorro declarou que o gato late 2 133

As representações das duas árvores no formato da MRS são idênticas, evidenciando que se trata uma ambiguidade espúria. A causa dessa  ambiguidade é a existência de dois complementadores do tipo *que*, **comps1** e **comps8**, gerados a partir do questionário:

```
comps1-complementizer-lex-item := complementizer-lex-item & basic-non-wh-word-lex &
  [ SYNSEM.LOCAL [ CAT [ MC na-or--,
                         VAL.COMPS.FIRST.LOCAL.CAT [ MC -,
                                                     HEAD.FORM finite ] ],
                   CONT.HOOK.INDEX.SF prop ] ].
```

```
comps8-complementizer-lex-item := complementizer-lex-item & basic-non-wh-word-lex &
  [ SYNSEM.LOCAL [ CAT [ MC na-or--,
                         VAL.COMPS.FIRST.LOCAL [ CONT.HOOK.INDEX.E.MOOD indicative,
                                                 CAT [ MC -,
                                                       HEAD.FORM finite ] ] ],
                   CONT.HOOK.INDEX.SF prop ] ].
```

A única diferença entre os dois é que o primeiro é subespecificado para o modo do verbo encaixado. A motivação para esses dois tipos foi que há verbos que não impõem um modo específico ao seu complemento oracional. Esse é o caso dos verbos de verbos de atividade mental (Mateus et al., 1989, p. 272):

> 18 o cachorro acredita que o gato late 2 151
> 19 o cachorro acredita que o gato lata 2 163

 
O objetivo desta _issue_ é eliminar essa ambiguidade, eventualmente modificando o código em TDL manualmente.

**Comment by leoalenc** [comment]
As seguintes sentenças também apresentam ambiguidade espúria:

![fez_com_que_ambig](https://user-images.githubusercontent.com/1275848/135688088-738328bd-ee66-4d19-a476-db56d3c7220b.png)

![fez_que_ambig](https://user-images.githubusercontent.com/1275848/135688106-3bad895f-fe0e-4146-84a5-f0e40767f065.png)

**Comment by arademaker** [comment]
Curiosidade. Estes screenshots são do LKB?

**Comment by leoalenc** [comment]
> Curiosidade. Estes screenshots são do LKB?

@arademaker, sim.
