### ISSUE TITLE
verbs governing inflected infinitival clauses wrongly classifyied

### ISSUE THREAD

**Issue by leoalenc** [LR-POR/PorGram#57]
Atualmente, temos:

```
ouvir_2 := inf-percep-verb-lex &
  [ STEM < "ouvir" >,
    SYNSEM.LKEYS.KEYREL.PRED "_ouvir_v_2_rel" ].

ver_2 := inf-percep-verb-lex &
  [ STEM < "ver" >,
    SYNSEM.LKEYS.KEYREL.PRED "_ver_v_2_rel" ].

sentir_2 := inf-percep-verb-lex &
  [ STEM < "sentir" >,
    SYNSEM.LKEYS.KEYREL.PRED "_sentir_v_2_rel" ].
```
Pela definição de `inf-percep-verb-lex` e pelos exemplos correspondentes, depreende-se que se trata de verbos que regem uma oração no infinitivo flexionado. 
No entanto, esses verbos são de controle do objeto. O mesmo problema afeta outros tipos. O objetivo desta _issue_ é fazer as correções necessárias no léxico.

**Comment by arademaker** [comment]
A gramática do inglês adota certas convenções para nomes de entradas lexicais e tipos:

Penso que precisamos começar a pensar em padrões semelhantes para que o código da gramática cresça de forma organizada

https://github.com/delph-in/docs/wiki/ErgLeTypes

**Comment by leoalenc** [comment]
Outros verbos passíveis de reclassificação são os seguintes:

```
fazer_3 := inf-caus-verb-lex &
  [ STEM < "fazer" >,
    SYNSEM.LKEYS.KEYREL.PRED "_fazer_v_3_rel" ].

mandar_2 := inf-caus-verb-lex &
  [ STEM < "mandar" >,
    SYNSEM.LKEYS.KEYREL.PRED "_mandar_v_2_rel" ].

deixar_2 := inf-caus-verb-lex &
  [ STEM < "deixar" >,
    SYNSEM.LKEYS.KEYREL.PRED "_deixar_v_2_rel" ]. 
```

**Comment by leoalenc** [comment]
Resolvido com https://github.com/LR-POR/PorGram/commit/2abc1fef6b9248bdac7fdfa35b6f200ebbbc267c.
