### ISSUE TITLE
replace "all" with "sup"

### ISSUE THREAD

**Issue by leoalenc** [LR-POR/PorGram#68]
Erroneamente, abreviei o caso da preposição *sobre* como *all* (de *allative*), quando, na verdade, deveria ser *sup* (de *superessive*), ver https://en.wiktionary.org/wiki/Thesaurus:grammatical_case#Instances.
Esta *issue* objetiva corrigir esse erro.

**Comment by leoalenc** [comment]
Problema resolvido.

**Comment by leoalenc** [comment]
Ainda ficaram ocorrências de *all* por substituir.

**Comment by leoalenc** [comment]
Em https://github.com/LR-POR/PorGram/commit/dd21486ecbd047781bd5576f5f744e64a9d969e1, fiz todas as substituições de *all* por *sup*, testando a gramática sobre os seguintes exemplos incluídos em `my-test_sentences.txt` e`results.txt`:

> 632 esse imposto incide sobre a renda 1 155
> 633 aqueles impostos incidiam sobre o consumo 1 148

**Comment by arademaker** [comment]
Seria bom termos em mente uma boa documentação da PorGram, futuramente, podemos ter uma instancia do LTB do @fbond rodando com a PorGram

Veja http://compling.hss.ntu.edu.sg/ltdb/cgi/ERG_1214//showtype.cgi?typ=aj_-_i-color-er_le

No lextypes.tdl, temos a tag `<ex>` e uma linha inicial com explicações, isto logo abaixo da definição e antes da TFS. 

```
aj_-_i-color-er_le := aj_-_i-color_lexent &
"""
Adj, color, only -er comparative
<ex>The cat is gray.
"""
  [ SYNSEM.LOCAL.CAT.HEAD.MINORS.ALTMIN comp_or_meas_rel ].
```

Finalmente, eu acho que as nomenclaturas precisam ser sempre explicadas. Pode ser dificil posteriormente o entendimento de que `all`  quer dizer `allative case` ou `sup` é `superessive`... eu até prefiro não abreviar, mas se for para abreviar, na docstring a abreviação deve ser explicada.

**Comment by arademaker** [comment]
Na ERG, existe uma distinção entre os Lexical Types e Lexical Entries, que recebem sufixo `le` (https://github.com/delph-in/docs/wiki/ErgLeTypes). Mas estes são definidos a partir de tipos como `n_pp_mc-of-lhc_lexent` e não sei o que seria o sufixo `lexent`.  Note que o nome `n_pp_mc-of-lhc_le` e a explicação `mc, PP-of comp, HC-LEX +` para mim são completamente incompreensíveis.

```
bank_n1 := n_pp_mc-of-lhc_le &
 [ ORTH < "bank" >,
   SYNSEM [ LKEYS.KEYREL.PRED "_bank_n_of_rel",
            PHON.ONSET con ] ].

n_pp_mc-of-lhc_le := n_pp_mc-of-lhc_lexent
"""
mc, PP-of comp, HC-LEX +
<ex>The University of Washington professor arrives.
"""

n_pp_mc-of-lhc_lexent := basic_noun_word & nonconj & mcna &
  [ INFLECTD na_or_-,
    SYNSEM mass_or_count_ppcomp_synsem &
	   [ LOCAL [ CAT.HC-LEX +,
		     CONT.HOOK.LTOP #ltop ],
	     MODIFD notmod & [ LPERIPH na ],
             LKEYS [ KEYREL.LBL #ltop,
		     --COMPKEY _of_p_sel_rel ] ] ].
.
```
