### ISSUE TITLE
organizing and cleaning up files 

### ISSUE THREAD

**Issue by arademaker** [LR-POR/PorGram#76]
1. [x] [choices](https://github.com/LR-POR/PorGram/blob/main/choices). Is this file different from the ones in https://github.com/LR-POR/PorGram/tree/main/grammar_choices? Can we move it to the folder? 
2. [x] [matrix-br-eng.txt](https://github.com/LR-POR/PorGram/blob/main/matrix-br-eng.txt) can we move it for the `test` folder?
3. [x] [my-test_sentences.txt](https://github.com/LR-POR/PorGram/blob/main/my-test_sentences.txt) same, can we move to `test` folder?
4. [x] out.stats, out.txt and [results.txt](https://github.com/LR-POR/PorGram/blob/main/results.txt) should be versioned?

**Comment by leoalenc** [comment]
The goal of this issue is to organize the files of the repository in a more transparent way, renaming and merging files, moving files to different folders and removing deprecated, useless files.

**Comment by leoalenc** [comment]
https://github.com/LR-POR/PorGram/commit/1df6505dd686c89e409b288af9ca3c92e228cbde solves these tasks:

> 1. [x]  [choices](https://github.com/LR-POR/PorGram/blob/main/choices). Is this file different from the ones in https://github.com/LR-POR/PorGram/tree/main/grammar_choices? Can we move it to the folder?

This folder contained different versions of the choices file, which can be tracked with the commit history. So this folder was deleted.

> 2. [x]  [matrix-br-eng.txt](https://github.com/LR-POR/PorGram/blob/main/matrix-br-eng.txt) can we move it for the `test` folder?

Done.

> 3. [x]  [my-test_sentences.txt](https://github.com/LR-POR/PorGram/blob/main/my-test_sentences.txt) same, can we move to `test` folder?

Done.

> 4. [x]  out.stats, out.txt and [results.txt](https://github.com/LR-POR/PorGram/blob/main/results.txt) should be versioned?

These files were moved to `test`.

**Comment by leoalenc** [comment]
@arademaker, to conclude and close the issue, should we move all lexicon files to a `lexicon` folder? If you think so, how to specify the path in the lisp script? There is one problem with this solution: `lexicon.tdl` is generated by the Grammar Matrix system, which puts this file in the main folder of the grammar.

**Comment by arademaker** [comment]
Eu posso adaptar o lkb/script depois que vc mover os arquivos de entradas lexicais para o folder "lexicon". 

Sugiro adotarmos alguma uniformidade nos nomes dos arquivos com entradas lexicais.

Sugiro mantemos o lexicon.tdl gerado pelo matrix no raiz e mantê-lo minimal, apenas com as mínimas entradas que forma feitas no matrix para exemplificar instâncias de tipos.

Faça a mudança e submeta PR do branch para o master que eu adapto o  lkb/script e faço o merge fechando este issue.

**Comment by arademaker** [comment]
O arquivo `random-sample-204-entries.tdl` tem apenas entradas lexicais mas foi deixado no raiz, alguma razão ?

**Comment by arademaker** [comment]
No commit 2369c34, ajustei o my-script, removi o my-globals.lsp atualizando o globals.lsp (experimentando evitar my-XX desnecessários).

**Comment by leoalenc** [comment]
> No commit [2369c34](https://github.com/LR-POR/PorGram/commit/2369c341d16fb91ed6ee4881edc3902ff3032a2e), ajustei o my-script, removi o my-globals.lsp atualizando o globals.lsp (experimentando evitar my-XX desnecessários).

Resolvido com https://github.com/LR-POR/PorGram/commit/b55ec46f066bbb928487677b326134897e9b9232.

**Comment by leoalenc** [comment]
> O arquivo `random-sample-204-entries.tdl` tem apenas entradas lexicais mas foi deixado no raiz, alguma razão ?

Resolvido com https://github.com/LR-POR/PorGram/commit/b55ec46f066bbb928487677b326134897e9b9232.

**Comment by arademaker** [comment]
para fechar este issue, falta apenas mover o [my-test-lexicon.tdl](https://github.com/LR-POR/PorGram/blob/main/my-test-lexicon.tdl)
